-- Generated by the database client.
CREATE TABLE a_branch(
    id SERIAL NOT NULL,
    name text,
    categoryid integer,
    createdat timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE a_category(
    id SERIAL NOT NULL,
    name text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    homebase integer
);

-- Generated by the database client.
CREATE TABLE a_class(
    id SERIAL NOT NULL,
    homebase integer,
    grade integer,
    major integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE a_grade(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE a_graduation(
    id SERIAL NOT NULL,
    userid integer,
    agency varchar(255),
    description text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE a_homebase(
    id SERIAL NOT NULL,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE a_major(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE a_periode(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    isactive boolean DEFAULT false,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE a_subject(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    cover text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    categoryid integer,
    branchid integer,
    presensi integer,
    attitude integer,
    daily integer,
    final integer,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE at_subject(
    id SERIAL NOT NULL,
    teacher integer NOT NULL,
    subject integer NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE c_answer(
    id SERIAL NOT NULL,
    exam integer,
    student integer,
    question integer,
    mc text,
    essay text,
    correct text,
    point integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE c_bank(
    id SERIAL NOT NULL,
    homebase integer,
    teacher integer,
    subject integer,
    btype text NOT NULL,
    name varchar(255) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE c_class(
    id SERIAL NOT NULL,
    exam integer,
    classid integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE c_ebank(
    id SERIAL NOT NULL,
    exam integer,
    bank integer,
    pg integer,
    essay integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE c_exam(
    id SERIAL NOT NULL,
    homebase integer,
    teacher integer,
    name varchar(255) NOT NULL,
    duration integer NOT NULL,
    isactive boolean DEFAULT true,
    isshuffle boolean DEFAULT false,
    mc_score integer NOT NULL,
    essay_score integer NOT NULL,
    token text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE c_question(
    id SERIAL NOT NULL,
    bank integer,
    qtype integer NOT NULL,
    question text NOT NULL,
    a text,
    b text,
    c text,
    d text,
    e text,
    qkey text,
    poin integer DEFAULT 0,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE cl_students(
    id SERIAL NOT NULL,
    homebase integer,
    periode integer,
    classid integer,
    student integer,
    student_name varchar(255) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE db_city(
    id character(4) NOT NULL,
    provinceid character(2) NOT NULL,
    name varchar(255) NOT NULL
);


-- Generated by the database client.
CREATE TABLE db_district(
    id character(7) NOT NULL,
    cityid character(4) NOT NULL,
    name varchar(255) NOT NULL
);

-- Generated by the database client.
CREATE TABLE db_family(
    id SERIAL NOT NULL,
    userid integer,
    name text,
    gender text,
    birth_date date,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);



-- Generated by the database client.
CREATE TABLE db_province(
    id character(2) NOT NULL,
    name varchar(255) NOT NULL
);


-- Generated by the database client.
CREATE TABLE db_student(
    id SERIAL NOT NULL,
    userid integer,
    homebaseid integer,
    homebase_name varchar(255),
    entryid integer,
    entry_name varchar(255),
    nis text,
    nisn text,
    name text,
    gender varchar(255),
    birth_place text,
    birth_date date,
    height text,
    weight text,
    head text,
    order_number text,
    siblings text,
    provinceid character(2),
    province_name text,
    cityid character(4),
    city_name text,
    districtid character(7),
    district_name text,
    villageid character(20),
    village_name text,
    postal_code text,
    address text,
    father_nik varchar(50),
    father_name varchar(255),
    father_birth_place varchar(255),
    father_birth_date date,
    father_job text,
    father_phone text,
    mother_nik varchar(50),
    mother_name varchar(255),
    mother_birth_place varchar(255),
    mother_birth_date date,
    mother_job text,
    mother_phone text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE db_village(
    id character(20) NOT NULL,
    districtid character(20),
    name varchar(255)
);


-- Generated by the database client.
CREATE TABLE l_attendance(
    id SERIAL NOT NULL,
    periode integer,
    classid integer,
    subjectid integer,
    studentid integer,
    note text,
    day_date date,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    teacher_id integer
);


-- Generated by the database client.
CREATE TABLE l_attitude(
    id SERIAL NOT NULL,
    student_id integer,
    subject_id integer,
    class_id integer,
    periode_id integer,
    chapter_id integer,
    teacher_id integer,
    semester integer,
    month varchar(20),
    kinerja integer,
    kedisiplinan integer,
    keaktifan integer,
    percaya_diri integer,
    catatan_guru text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    rata_rata numeric(5,2) GENERATED ALWAYS AS ((((COALESCE(kinerja, 0) + COALESCE(kedisiplinan, 0)) + COALESCE(keaktifan, 0)) + COALESCE(percaya_diri, 0)) / NULLIF(num_nonnulls(kinerja, kedisiplinan, keaktifan, percaya_diri), 0)) STORED,
    CONSTRAINT l_attitude_keaktifan_check CHECK (((keaktifan >= 0) AND (keaktifan <= 100))),
    CONSTRAINT l_attitude_kedisiplinan_check CHECK (((kedisiplinan >= 0) AND (kedisiplinan <= 100))),
    CONSTRAINT l_attitude_kinerja_check CHECK (((kinerja >= 0) AND (kinerja <= 100))),
    CONSTRAINT l_attitude_month_check CHECK (((month)::text = ANY (ARRAY[('Januari'::character varying)::text, ('Februari'::character varying)::text, ('Maret'::character varying)::text, ('April'::character varying)::text, ('Mei'::character varying)::text, ('Juni'::character varying)::text, ('Juli'::character varying)::text, ('Agustus'::character varying)::text, ('September'::character varying)::text, ('Oktober'::character varying)::text, ('November'::character varying)::text, ('Desember'::character varying)::text]))),
    CONSTRAINT l_attitude_percaya_diri_check CHECK (((percaya_diri >= 0) AND (percaya_diri <= 100))),
    CONSTRAINT l_attitude_semester_check CHECK (((semester >= 1) AND (semester <= 2)))
);
CREATE UNIQUE INDEX l_attitude_unique_key ON public.l_attitude USING btree (student_id, subject_id, class_id, chapter_id, month, semester);
CREATE INDEX idx_attitude_student_subject ON public.l_attitude USING btree (student_id, subject_id);
CREATE INDEX idx_attitude_class_chapter ON public.l_attitude USING btree (class_id, chapter_id);
CREATE INDEX idx_attitude_month ON public.l_attitude USING btree (month);
CREATE UNIQUE INDEX idx_attitude_unique ON public.l_attitude USING btree (student_id, subject_id, class_id, chapter_id, month, semester);



-- Generated by the database client.
CREATE TABLE l_cclass(
    id SERIAL NOT NULL,
    chapter integer,
    classid integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE l_chapter(
    id SERIAL NOT NULL,
    subject integer,
    teacher integer,
    title text NOT NULL,
    target text NOT NULL,
    order_number integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE l_content(
    id SERIAL NOT NULL,
    chapter integer,
    title text NOT NULL,
    target text NOT NULL,
    order_number integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE l_file(
    id SERIAL NOT NULL,
    content integer,
    title text NOT NULL,
    file text,
    video text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE l_finalscore(
    id SERIAL NOT NULL,
    periode integer,
    semester integer,
    teacherid integer,
    subjectid integer,
    classid integer,
    studentid integer,
    score integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT l_finaltest_periode_fkey FOREIGN key(periode) REFERENCES a_periode(id),
    CONSTRAINT l_finaltest_teacher_fkey FOREIGN key(teacherid) REFERENCES u_teachers(id),
    CONSTRAINT l_finaltest_subject_fkey FOREIGN key(subjectid) REFERENCES a_subject(id),
    CONSTRAINT l_finaltest_class_fkey FOREIGN key(classid) REFERENCES a_class(id),
    CONSTRAINT l_finaltest_student_fkey FOREIGN key(studentid) REFERENCES u_students(id),
    CONSTRAINT l_finaltest_score_check CHECK (((score >= 0) AND (score <= 100)))
);


-- Generated by the database client.
CREATE TABLE l_formative(
    id SERIAL NOT NULL,
    student_id integer,
    subject_id integer,
    class_id integer,
    periode_id integer,
    chapter_id integer,
    teacher_id integer,
    semester integer,
    month varchar(20),
    f_1 integer,
    f_2 integer,
    f_3 integer,
    f_4 integer,
    f_5 integer,
    f_6 integer,
    f_7 integer,
    f_8 integer,
    rata_rata numeric(5,2),
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT l_formative_f_1_check CHECK (((f_1 >= 0) AND (f_1 <= 100))),
    CONSTRAINT l_formative_f_2_check CHECK (((f_2 >= 0) AND (f_2 <= 100))),
    CONSTRAINT l_formative_f_3_check CHECK (((f_3 >= 0) AND (f_3 <= 100))),
    CONSTRAINT l_formative_f_4_check CHECK (((f_4 >= 0) AND (f_4 <= 100))),
    CONSTRAINT l_formative_f_5_check CHECK (((f_5 >= 0) AND (f_5 <= 100))),
    CONSTRAINT l_formative_f_6_check CHECK (((f_6 >= 0) AND (f_6 <= 100))),
    CONSTRAINT l_formative_f_7_check CHECK (((f_7 >= 0) AND (f_7 <= 100))),
    CONSTRAINT l_formative_f_8_check CHECK (((f_8 >= 0) AND (f_8 <= 100))),
    CONSTRAINT l_formative_month_check CHECK (((month)::text = ANY (ARRAY[('Januari'::character varying)::text, ('Februari'::character varying)::text, ('Maret'::character varying)::text, ('April'::character varying)::text, ('Mei'::character varying)::text, ('Juni'::character varying)::text, ('Juli'::character varying)::text, ('Agustus'::character varying)::text, ('September'::character varying)::text, ('Oktober'::character varying)::text, ('November'::character varying)::text, ('Desember'::character varying)::text]))),
    CONSTRAINT l_formative_semester_check CHECK (((semester >= 1) AND (semester <= 2)))
);
CREATE UNIQUE INDEX l_formative_unique_entry_key ON public.l_formative USING btree (student_id, subject_id, class_id, chapter_id, month, semester);
CREATE INDEX idx_formative_class_chapter ON public.l_formative USING btree (class_id, chapter_id);
CREATE INDEX idx_formative_month ON public.l_formative USING btree (month);
CREATE INDEX idx_formative_student_subject ON public.l_formative USING btree (student_id, subject_id);
CREATE UNIQUE INDEX idx_formative_unique ON public.l_formative USING btree (student_id, subject_id, class_id, chapter_id, month, semester);


-- Generated by the database client.
CREATE TABLE l_summative(
    id SERIAL NOT NULL,
    student_id integer,
    subject_id integer,
    class_id integer,
    periode_id integer,
    chapter_id integer,
    teacher_id integer,
    semester integer,
    month varchar(20),
    oral integer,
    written integer,
    project integer,
    performance integer,
    rata_rata numeric(5,2),
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT l_summative_month_check CHECK (((month)::text = ANY (ARRAY[('Januari'::character varying)::text, ('Februari'::character varying)::text, ('Maret'::character varying)::text, ('April'::character varying)::text, ('Mei'::character varying)::text, ('Juni'::character varying)::text, ('Juli'::character varying)::text, ('Agustus'::character varying)::text, ('September'::character varying)::text, ('Oktober'::character varying)::text, ('November'::character varying)::text, ('Desember'::character varying)::text]))),
    CONSTRAINT l_summative_oral_check CHECK (((oral >= 0) AND (oral <= 100))),
    CONSTRAINT l_summative_performance_check CHECK (((performance >= 0) AND (performance <= 100))),
    CONSTRAINT l_summative_project_check CHECK (((project >= 0) AND (project <= 100))),
    CONSTRAINT l_summative_semester_check CHECK (((semester >= 1) AND (semester <= 2))),
    CONSTRAINT l_summative_written_check CHECK (((written >= 0) AND (written <= 100)))
);
CREATE UNIQUE INDEX l_summative_unique_entry_key ON public.l_summative USING btree (student_id, subject_id, class_id, chapter_id, month, semester);
CREATE INDEX idx_summative_class_chapter ON public.l_summative USING btree (class_id, chapter_id);
CREATE INDEX idx_summative_month ON public.l_summative USING btree (month);
CREATE INDEX idx_summative_student_subject ON public.l_summative USING btree (student_id, subject_id);
CREATE UNIQUE INDEX idx_summative_unique ON public.l_summative USING btree (student_id, subject_id, class_id, chapter_id, month, semester);

-- Generated by the database client.
CREATE TABLE l_weighting(
    id SERIAL NOT NULL,
    teacherid integer NOT NULL,
    subjectid integer NOT NULL,
    presensi smallint NOT NULL,
    attitude smallint NOT NULL,
    daily smallint NOT NULL,
    CONSTRAINT l_weighting_attitude_check CHECK (((attitude >= 0) AND (attitude <= 100))),
    CONSTRAINT l_weighting_daily_check CHECK (((daily >= 0) AND (daily <= 100))),
    CONSTRAINT l_weighting_presensi_check CHECK (((presensi >= 0) AND (presensi <= 100))),
    CONSTRAINT total_weight_must_be_100 CHECK ((((presensi + attitude) + daily) = 100))
);
CREATE UNIQUE INDEX l_weighting_teacherid_subjectid_key ON public.l_weighting USING btree (teacherid, subjectid);
CREATE UNIQUE INDEX unique_teacher_subject ON public.l_weighting USING btree (teacherid, subjectid);



-- Generated by the database client.
CREATE TABLE logs(
    id SERIAL NOT NULL,
    student integer,
    teacher integer,
    admin integer,
    exam integer,
    ip text,
    browser text,
    islogin boolean,
    ispenalty boolean,
    isactive boolean,
    isdone boolean,
    "action" text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE t_categories(
    id SERIAL NOT NULL,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE t_examiner(
    id SERIAL NOT NULL,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE t_indicators(
    id SERIAL NOT NULL,
    name text NOT NULL,
    category_id integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE t_juz(
    id SERIAL NOT NULL,
    name varchar(100) NOT NULL
);


-- Generated by the database client.
CREATE TABLE t_juzitems(
    id SERIAL NOT NULL,
    juz_id integer,
    surah_id integer,
    from_ayat numeric,
    to_ayat numeric,
    lines numeric
);


-- Generated by the database client.
CREATE TABLE t_process(
    id SERIAL NOT NULL,
    userid integer,
    periode_id integer,
    type_id integer,
    juz_id integer,
    surah_id integer,
    from_count integer,
    to_count integer,
    from_line integer,
    to_line integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE t_scoring(
    id SERIAL NOT NULL,
    userid integer,
    periode_id integer,
    examiner_id integer,
    type_id integer,
    category_id integer,
    indicator_id integer,
    poin text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE t_surah(
    id SERIAL NOT NULL,
    name varchar(100) NOT NULL,
    ayat integer NOT NULL,
    lines integer
);


-- Generated by the database client.
CREATE TABLE t_target(
    id SERIAL NOT NULL,
    grade_id integer,
    juz_id integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE t_type(
    id SERIAL NOT NULL,
    name varchar(100) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE u_admin(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    password text NOT NULL,
    level text DEFAULT 'admin'::text,
    activation text,
    isactive boolean DEFAULT false,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE u_parents(
    id SERIAL NOT NULL,
    studentid integer,
    email text NOT NULL,
    name text NOT NULL,
    password text NOT NULL,
    level text DEFAULT 'parent'::text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX u_parents_email_key ON public.u_parents USING btree (email);


-- Generated by the database client.
CREATE TABLE u_students(
    id SERIAL NOT NULL,
    homebase integer,
    entry integer,
    name text NOT NULL,
    nis text,
    password text,
    level text DEFAULT 'student'::text,
    gender varchar(255),
    isactive boolean DEFAULT true,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    periode integer,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE u_teachers(
    id SERIAL NOT NULL,
    username text NOT NULL,
    name text NOT NULL,
    email text,
    img text,
    homebase integer NOT NULL,
    homeroom boolean DEFAULT false,
    class integer,
    phone text,
    password text NOT NULL,
    gender varchar(10) NOT NULL,
    level text DEFAULT 'teacher'::text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);



INSERT INTO configurations (category, key, value, description, type) VALUES
('app', 'app_name', 'NIBS', 'Nama Aplikasi', 'text'),
('app', 'app_logo', '/assets/web/logo.png', 'URL Logo Aplikasi', 'image'),
('app', 'app_favicon', '/assets/web/favicon.png', 'URL Favicon Aplikasi', 'image'),
('smtp', 'smtp_host', 'smtp.gmail.com', 'SMTP Host Server', 'string'),
('smtp', 'smtp_port', '465', 'SMTP Port', 'number'),
('smtp', 'smtp_user', 'web.nuraida@nibs.sch.id', 'SMTP Email User', 'string'),
('smtp', 'smtp_pass', 'xptnzwkbcyseuyjv', 'SMTP App Password', 'password'), -- Tipe 'password' agar di UI frontend inputnya titik-titik (hidden)
('smtp', 'smtp_from_email', 'no-reply@toserba.com', 'Email Pengirim', 'string'),
('smtp', 'smtp_from_name', 'NIBS', 'Nama Pengirim Email', 'string');


-- Masukkan ini ke database Anda
INSERT INTO configurations (category, key, value, description, type) VALUES 
('metadata', 'meta_title', 'EduCore - Sistem Manajemen Sekolah', 'Judul Website (Title Tag)', 'string'),
('metadata', 'meta_description', 'Aplikasi manajemen sekolah all-in-one. Kelola database siswa, ujian online (CBT), dan LMS.', 'Deskripsi Website (SEO)', 'text'),
('metadata', 'meta_keywords', 'aplikasi sekolah, lms, cbt, tahfiz', 'Kata Kunci (Keywords)', 'text'),
('metadata', 'meta_author', 'almadev', 'Penulis/Developer', 'string'),
('metadata', 'og_title', 'EduCore - Solusi Manajemen Sekolah', 'Judul Open Graph (Sosmed)', 'string'),
('metadata', 'og_description', 'Platform terintegrasi untuk CBT, LMS, Tahfiz.', 'Deskripsi Open Graph', 'text'),
('metadata', 'og_image', 'https://lms.nibs.sch.id/assets/web/logo.png', 'URL Gambar Share Link', 'image')
